<?php
include("inc/header.php");
?>
<body>
<?php
include("inc/navbar.php");
include("inc/all-objects.php");
include("inc/templates/all-objects.php");
include("inc/templates/detail-objects.php");
include("inc/modals/more-info.php");
include("inc/scripts.php");
?>   
</body>
</html>